# we can validate our .yml config
# gem install travis --no-rdoc --no-ri
# travis lint [path to your .travis.yml]

# we'll try to use container based infrastructure
sudo: false
# sudo: required

    
language: java

jdk:
  - oraclejdk8

    
git:
  depth: 1


services:
  - docker

before_install:
- docker pull altsoft/platypus
- docker run -v `pwd`:/platypus altsoft/platypus /bin/sh -c "ant -Dlibs.javaee-web-api-7.0.classpath=/usr/local/apache-tomcat-8.0.36/lib/servlet-api.jar:/usr/local/apache-tomcat-8.0.36/lib/websocket-api.jar -f /platypus/application/src/group/build.xml clean compile"

# - docker ps -a
# - docker run carlad/sinatra /bin/sh -c "cd /root/sinatra; bundle exec rake test"

# Headless testing in browsers