# we can validate our .yml config
# gem install travis --no-rdoc --no-ri
# travis lint [path to your .travis.yml]

# we'll try to use container based infrastructure
sudo: false
# sudo: required

language: java


jdk:
  - oraclejdk8

    
git:
  depth: 1


services:
  - docker

before_install:
  - git clone --depth=1 https://github.com/altsoft/PlatypusTests.git platypusTests
  - docker pull altsoft/platypus
  - docker pull altsoft/testdb
  - docker run --name=testDb -p 3307:3306 -d altsoft/testdb
  # - sleep 60  
  - docker run --name=platypus -d -v `pwd`:/platypus -v `pwd`/platypusTests:/platypusTests --link testDb:testDb -p 8500:8500 -p 8080:8080 altsoft/platypus 
  # - docker/platypus.js/installTravisJava.sh
  # - echo $(java -version)
  - sleep 120

before_script:
  - docker exec -i -t platypus ping testDb -c 5
  - docker ps -a
  # - docker exec platypus /bin/bash -c "Xvfb :1 -screen 0 640x480x24 -fbdir /var/tmp&"
  # - export DISPLAY=:99.0
  # - sh -e /etc/init.d/xvfb start
  # - sleep 5

script:
  - docker exec platypus /bin/bash -c "export DISPLAY=localhost:1.0 && DISPLAY=localhost:1.0 ant -Dsun.jnu.encoding=UTF-8 -Dfile.encoding=UTF-8 -Dplatypus-server.url=platypus://localhost:8500 -Dplatypus-server.user=testuser2 -Dplatypus-server.password=test -Dapplication.source.path=app -Dservlet-container.url=http://localhost:8080/p-tests -Dservlet-container.user=testuser2 -Dservlet-container.password=test -Ddatasource.1.name=eas -Ddatasource.1.dburl="jdbc:mysql://localhost:3307/eas" -Ddatasource.1.dbuser=test -Ddatasource.1.dbpassword=test -Ddatasource.1.dbschema=eas -Ddatasource.2.name=easHR  -Ddatasource.2.dburl=jdbc:mysql://localhost:3307/hr -Ddatasource.2.dbuser=test -Ddatasource.2.dbpassword=test -Ddatasource.2.dbschema=hr -Ddatasource.default=eas -Dtestsource.url=file:///platypusTests/ -Dlibs.javaee-web-api-7.0.classpath=/usr/local/apache-tomcat-8.0.39/lib/servlet-api.jar:/usr/local/apache-tomcat-8.0.39/lib/websocket-api.jar -f /platypus/application/src/group/build.xml -Dlibs.junit_4.classpath=/usr/local/ant/lib/junit4.jar -Dlibs.hamcrest.classpath=/usr/local/ant/lib/hamcrest-core.jar test"
