# we can validate our .yml config
# gem install travis --no-rdoc --no-ri
# travis lint [path to your .travis.yml]

# we'll try to use container based infrastructure
sudo: false
# sudo: required

    
language: java

jdk:
  - oraclejdk8

    
git:
  depth: 1


services:
  - docker

before_install:
- docker pull altsoft/platypus
- docker run -v `pwd`:/platypus altsoft/platypus /bin/sh -c "ant -Dlibs.javaee-web-api-7.0.classpath=/usr/local/apache-tomcat-8.0.36/lib/servlet-api.jar:/usr/local/apache-tomcat-8.0.36/lib/websocket-api.jar -f /platypus/application/src/group/build.xml clean compile"


script:
- docker run -v `pwd`:/platypus altsoft/platypus /bin/sh -c "ant -Dlibs.javaee-web-api-7.0.classpath=/usr/local/apache-tomcat-8.0.36/lib/servlet-api.jar:/usr/local/apache-tomcat-8.0.36/lib/websocket-api.jar -f /platypus/application/src/group/build.xml -Dlibs.junit_4.classpath=/usr/local/ant/lib/junit4.jar -Dlibs.hamcrest.classpath=/usr/local/ant/lib/hamcrest-core.jar -Dnb.internal.action.name=test -Dignore.failing.tests=true test"

ant -DnativeSever.url=platypus://localhost:8500 -DnativeSever.user=testuser2 -DnativeSever.password=test -Dapplication.source.path=app -DwebSever.url=http://localhost:8080/p-tests -DwebSever.user=testuser2 -DwebSever.password=test -Ddatasource.name.1=eas -Ddatasource.dburl.1=jdbc:mysql://192.168.10.205:3306/eas -Ddatasource.dbuser.1=test2 -Ddatasource.dbpassword.1=test2 -Ddatasource.dbschema.1=eas -Ddatasource.name.2=easHR  -Ddatasource.dburl.2=jdbc:mysql://192.168.10.205:3306/hr  -Ddatasource.dbuser.2=test2 -Ddatasource.dbpassword.2=test2 -Ddatasource.dbschema.2=hr -Ddatasource.default=eas -Dtestsource.url=file:///home/jskonst/workspace/Altsoft/PlatypusTests/ -Dlibs.javaee-web-api-7.0.classpath=/home/jskonst/apache-tomcat-8.0.30/lib/servlet-api.jar:/home/jskonst/apache-tomcat-8.0.30/lib/websocket-api.jar -f ./application/src/group/build.xml -Dnb.internal.action.name=test -Dignore.failing.tests=true test