# we can validate our .yml config
# gem install travis --no-rdoc --no-ri
# travis lint [path to your .travis.yml]

# we'll try to use container based infrastructure
sudo: required
# sudo: required

addons:
  apt:
    packages:
      - oracle-java8-installer

language: java


jdk:
  - oraclejdk8

    
git:
  depth: 1
