# we can validate our .yml config
# gem install travis --no-rdoc --no-ri
# travis lint [path to your .travis.yml]

# we'll try to use container based infrastructure
sudo: false
# sudo: required

    
language: java

jdk:
  - oraclejdk8

    
git:
  depth: 1


services:
  - docker

# before_install:
# - docker pull carlad/sinatra
# - docker run -d -p 127.0.0.1:80:4567 carlad/sinatra /bin/sh -c "cd /root/sinatra; bundle exec foreman start;"
# - docker ps -a
# - docker run carlad/sinatra /bin/sh -c "cd /root/sinatra; bundle exec rake test"

# Headless testing in browsers